export default {
  wrap: { flex: 1 },
  img_wrap: {
    position: "relative",
    marginBottom: 10,
    width: "100%",
    // height: 250,
    flex: 1,
    alignItems: "center",
    flexDirection: "column",
    justifyContent: "center",
  },
  imgFood: { position: "absolute", left: 0, width: "100%", height: 250 },
  text_wrap: { backgroundColor: "rgba(256, 256, 256, 0.8)", padding: 10 },
  week_text: {
    fontSize: 30,
    color: "#cd0000",
  },
  instructions: {
    color: "#888",
    fontSize: 18,
    marginTop: 20,
    marginBottom: 10,
    marginHorizontal: 15,
  },
  textMain: { fontSize: 16, textAlign: "center", paddingTop: 10 },
  buttonStart: { backgroundColor: "#cd0000", padding: 20, borderRadius: 5 },
  buttonStartText: { fontSize: 20, color: "#fff" },
  wrap_main: { flex: 3 },
  divider: {
    width: 100,
    borderTopColor: "whitesmoke",
    borderStyle: "solid",
    borderTopWidth: 2,
    marginTop: 0,
    marginBottom: 10,
  },
  mealTimeText: {
    marginTop: 10,
  },
  dishCompleted: {
    padding: 10,
    backgroundColor: "#99ffbb",
    width: 300,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  dishMissing: {
    padding: 10,
    backgroundColor: "#ff9999",
    width: 300,
    flexDirection: "row",
    justifyContent: "space-between",
  },
};
